### ISSUE TITLE
How to use this? 

### ISSUE THREAD

**Issue by dvcrn** [spect88/cocoro-mqtt#1]
Hi! Stumbled upon this while checking if I can replace HomeBridge with HASS. I hooked this up with my credentials to my MQTT broker but nothing happens. Are any additional steps required?

**Comment by spect88** [comment]
There are no steps other than the 2 listed in the README.

Sorry about the late response, I haven't used it in a while and wanted to check with my Cocoro Air device. When I tried just now I'm getting auth errors, so it's possible they've changed something in the private API. Either that or my credentials expired?

Did you have any luck in the meantime?

**Comment by dvcrn** [comment]
The issue was that we're using different devices. Your integration expects a Purifier, but I'm using a Sharp Airconditioner 😅 they have different properties and different functions they support 

I went ahead and built ported own Python SDK for the Cocoro Air API, and a quick HA plugin for it 

- https://github.com/dvcrn/sharp-cocoro
- https://github.com/dvcrn/ha-sharp-cocoro
